## Advance operation with Business examples

In [5]:
import numpy as np
import matplotlib.pyplot as plt

Matplotlib is building the font cache; this may take a moment.


In [10]:
# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]

sales_data = np.array([
    [1, 150000, 180000, 220000, 250000], # Paradise
    [2, 120000, 14000, 160000, 180000], # Pizza Hut
    [3, 100000, 110000, 120000, 130000], # KFC
    [4, 80000, 90000, 100000, 110000], # Burger King
    [5, 60000, 70000, 80000, 90000], # McDonald
])

print('=== Nox Cart sales analysis ===')
print('shape:', sales_data.shape)
print("first three restaturants: \n", sales_data[0:3]) # selects 0-2 row and all col
print("only last 3 year sales of first 3 restaurants : \n", sales_data[:, 2:])  # [selects all row, select cols after first 2]


=== Nox Cart sales analysis ===
shape: (5, 5)
first three restaturants: 
 [[     1 150000 180000 220000 250000]
 [     2 120000  14000 160000 180000]
 [     3 100000 110000 120000 130000]]
only last 3 year sales of first 3 restaurants : 
 [[180000 220000 250000]
 [ 14000 160000 180000]
 [110000 120000 130000]
 [ 90000 100000 110000]
 [ 70000  80000  90000]]


In [ ]:
# total sales per year
sum = np.sum(sales_data[:, 1:], axis=1)  # restaturants yearly total

print("total sales per year : ", np.sum(sum, axis=0)) # complete sales total from all restaurants ...



total sales per year :  2414000
